SEP6-11 Search for movies & people
HolaSombreros/SEP6 pull request #28
Opened 2023-05-17 15:00 UTC by RealFoXsTeRDOTA

2023-05-17 15:13 UTC, HolaSombreros commented on src/MovieManagement/Components/Search.razor.cs
> +﻿using MovieManagement.ViewModels.Search;
this should be in global usings, no?

2023-05-17 15:13 UTC, HolaSombreros commented on src/MovieManagement/Pages/SearchResults/SearchResults.razor.cs
> +﻿using MovieManagement.ViewModels.Search;
global usings?

2023-05-17 15:13 UTC, HolaSombreros commented on src/MovieManagement/appsettings.json
> +    "HostKey": "code=moviemanagementauthBz_wcc9CwsHGuSIAnTIgTq",
delete this

2023-05-17 15:13 UTC, HolaSombreros commented on src/MovieManagement/Shared/Sidebar.razor.cs
> +﻿using MovieManagement.ViewModels.Search;
global usings

2023-05-17 15:26 UTC, HolaSombreros approved these changes

2023-05-17 15:36 UTC, vladdirlea2002 requested changes

2023-05-17 15:36 UTC, vladdirlea2002 commented on src/MovieManagement/Components/SearchResults/SearchMovieCard.razor
> +@code {
inside code

2023-05-17 15:36 UTC, vladdirlea2002 commented on src/MovieManagement/Components/SearchResults/SearchPersonCard.razor
> +@code {
inside code

2023-05-17 15:36 UTC, vladdirlea2002 commented on src/MovieManagement/GlobalUsings.cs
> -global using System.Text.Json.Serialization;
I struggled to order them alphabetically. Please do so as well so we don't end up with 100 duplicates

2023-05-17 15:36 UTC, vladdirlea2002 commented on src/MovieManagement/Shared/MainLayout.razor.css
> +/*::-webkit-scrollbar {
Make it visible and display it if you want it on buddy. Don't comment it and let it be displayed without css -.-'

2023-05-18 08:03 UTC, stefaniatomuta approved these changes

2023-05-18 08:24 UTC, vladdirlea2002 approved these changes

2023-05-18 08:29 UTC, merged